apiVersion: 1

datasources:
  - name: InfluxDB-MiniPlant
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: mini-plant
      defaultBucket: iot-data
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    isDefault: true
    editable: true